image: alpine:latest

stages:
- build

build:
    stage: build
    tags:
        - shared-fi
    variables:
        CXX: clang
    script:
        - apk add cmake
        - apk add clang
        - cmake
        - make
    artifacts:
        untracked: true
