image: alpine:latest

stages:
- build

build:
    stage: build
    tags:
        - shared-fi
    variables:
        CXX: clang
    script:
        - apk add make cmake clang libc6-compat
        - cmake .
        - make
    artifacts:
        untracked: true
