image: alpine:clang-3.8

stages:
- build

build:
    stage: build
    tags:
        - shared-fi
    variables:
        CC: clang
        CXX: clang++
    script:
        - cmake .
        - make
    artifacts:
        untracked: true
