#! /usr/bin/env bash

#add the necessary modules 
#(and ignore errors in case they are already loaded)
module add gcc 2> /dev/null
module add cmake-3.6.2 2> /dev/null


#generate the CMake config inside the build directory
mkdir -p build
cd build
cmake ..

#build only the neural network without tests (to conserve time)
make -j13 pv021_nn

#run and (hopefully) profit
./pv021_nn

#link the output predictions
cp outputFile.csv ../actualPredictions
cd ..
